export enum EstablishmentStatus {
  REGISTRO_PENDIENTE_INSPECCION = 'Registro PENDIENTE DE INSPECCION',
  REVISAR_REGISTROS = 'Revisar en "Ver Registros"',
  SIN_REGISTRO = 'Sin Registro',
  CERRADO_SRI = 'CERRADO SRI'
}

export enum EstablishmentActivity {
  AGENCIAMIENTO_TURISTICO = 'AGENCIAMIENTO TURÍSTICO AGENCIA OPERADORA DE TURISMO',
  ORGANIZADORES_EVENTOS = 'ORGANIZADORES DE EVENTOS, CONGRESOS Y CONVENCIONES'
}